spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bruce_test?serverTimezone=UTC
    username: root
    password: Aa-123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  #aop:
    #proxy-target-class: false